services:
  - type: web
    name: my-todo-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    disk:
      name: persistent-disk
      mountPath: /app/data
      sizeGB: 1
